### PR TITLE
:sparkles: feat: add serveral platforms

### PR DESCRIPTION
**Pull request by FurryR**
# Proposed Changes

- **feat** Added **ElectraMod** and **XPLab** nightly support.

### CODE REVIEW

**Comment by SimonShiki** [comment]
also add these platforms in moth plz

**Review by SimonShiki — APPROVED** [review]

**Comment by Aness6040** [comment]
thx @FurryR for the PR

**Comment by Aness6040** [comment]
why check failed?

**Comment by FurryR** [comment]
@SimonShiki Moth related PR: https://github.com/EurekaScratch/moth/pull/15

**Pull request merged**
