### PR TITLE
  🔧 chore: transfer to EurekaScratch

### PR DESCRIPTION
**Pull request by jexjws**
对了，package.json字段里面的"author"，一并改成EurekaScratch？

### CODE REVIEW

**Comment by SimonShiki** [comment]
你真是火速发pr

**Review by SimonShiki — CHANGES_REQUESTED** [review]
change commit message.

``:wrench: chore: transfer to EurekaScratch``

**Review by jexjws — COMMENTED** [review]
:wrench: chore: transfer to EurekaScratch

**Comment by jexjws** [comment]
> 🔧 chore: transfer to EurekaScratch

图片

啊 这个怎么发了个评论

**Comment by jexjws** [comment]
> change commit message.
> 
> `:wrench: chore: transfer to EurekaScratch`

把pr标题改成 ` 🔧 chore: transfer to EurekaScratch` 就好了吗

**Comment by SimonShiki** [comment]
> > change commit message.
> > 
> > `:wrench: chore: transfer to EurekaScratch`
> 
> 把pr标题改成 ` 🔧 chore: transfer to EurekaScratch` 就好了吗

更改commit消息，和pr标题无关

**Comment by SimonShiki** [comment]
测

**Pull request merged**
